name: uasya
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/images/cendrawasih.png
    - assets/images/jalak_bali.png
    - assets/images/walik_solomon.jpg
    - assets/images/rangkong_papan.jpg
    - assets/images/taktarau_iblis.jpg
    - assets/images/Delimukan_Sulawesi.jpg
    - assets/images/anis_buru.jpg
    - assets/images/anis_geomalia.jpg
    - assets/images/sri_lanka.jpg
